version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - blog-network

  app:
    build: .
    container_name: blog-app
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - MYSQL_HOST=mysql
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - mysql
      - minio
    networks:
      - blog-network

  minio:
    image: minio/minio:latest
    container_name: blog-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  mysql-data:
  minio_data: 